disabled_rules:
- line_length
- function_parameter_count
- switch_case_alignment
- multiple_closures_with_trailing_closure
included:
excluded:
- Pods
- /Users/jongho/Desktop/Personal_Project/CommitGenerator/CommitGenerator/Resources/Color.swift


type_name:
 allowed_symbols: ["_"]


identifier_name:
 allowed_symbols: ["_"]
