disabled_rules:
- line_length
- function_parameter_count
- switch_case_alignment
- trailing_whitespace
- multiple_closures_with_trailing_closure
included:
excluded:
- Pods
- /Users/jonghopark/Desktop/Personnal_Project/Commit-Message-Generator/CommitGenerator/Resources/Color.swift
- /Users/jongho/Desktop/Personal_Project/CommitGenerator/CommitGenerator/View/ViewExtension.swift

type_name:
 allowed_symbols: ["_"]


identifier_name:
 allowed_symbols: ["_"]
